### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._six - Google Colab

### ISSUE THREAD

**Issue by AvidahRai** [hanchaoleng/ShapeConv#13]
"Traceback (most recent call last):
  File "/content/ShapeConv/tools/test.py", line 7, in <module>
    from rgbd_seg.runners import TestRunner
  File "/content/ShapeConv/tools/../rgbd_seg/runners/__init__.py", line 1, in <module>
    from .inference_runner import InferenceRunner
  File "/content/ShapeConv/tools/../rgbd_seg/runners/inference_runner.py", line 3, in <module>
    from ..models import build_model
  File "/content/ShapeConv/tools/../rgbd_seg/models/__init__.py", line 1, in <module>
    from .builder import build_model
  File "/content/ShapeConv/tools/../rgbd_seg/models/builder.py", line 5, in <module>
    from rgbd_seg.models.decoders import build_brick
  File "/content/ShapeConv/tools/../rgbd_seg/models/decoders/__init__.py", line 1, in <module>
    from .bricks import FusionBlock, JunctionBlock
  File "/content/ShapeConv/tools/../rgbd_seg/models/decoders/bricks.py", line 8, in <module>
    from ..utils import ConvModule, build_module
  File "/content/ShapeConv/tools/../rgbd_seg/models/utils/__init__.py", line 2, in <module>
    from .conv_module import ConvModule, ConvModules
  File "/content/ShapeConv/tools/../rgbd_seg/models/utils/conv_module.py", line 10, in <module>
    from rgbd_seg.models.utils.shape_conv import ShapeConv2d
  File "/content/ShapeConv/tools/../rgbd_seg/models/utils/shape_conv.py", line 9, in <module>
    from torch._six import container_abcs
ModuleNotFoundError: No module named 'torch._six'"

**Comment by hanchaoleng** [comment]
This project is developed based on torch1.7, it is recommended to use the corresponding version.
Or replace pair_(a) with (a,a), and remove the  'torch._six'

**Comment by AvidahRai** [comment]
Thanks for reply. 

Unfortunately on Google colab the earliest version we can download is 1.11.0
